development:
  host: 127.0.0.1
  adapter: mysql2
  encoding: utf8
  database: zeitwein_db
  username: zeitwein
  password: zeitwein
  pool: 5
  timeout: 5000

test:
  host: 127.0.0.1
  adapter: mysql2
  encoding: utf8
  database: zeitwein_db_test
  username: zeitwein
  password: zeitwein
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  database: ec2-54-204-41-178.compute-1.amazonaws.com
  username: db2lee6j7oult2
  password: test
  port: 5432
