defaults: &defaults
  app_key: '286l4d5gewypc4h'
  app_secret: 'x4m5azrwzmyvrxs'
  backup_path: '/Public/Backups/ <- folder inside dropbox' 
  heroku_app_name: 'zeitwein'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults